### ISSUE TITLE
Кейс с неопределенным адресом по IP в документации 

### ISSUE THREAD

**Issue by Sunsetboy** [ekomobile/dadata#17]
В документации на сайте не описан кейс, когда адрес не определен по IP

Пример
```
api := dadata.NewSuggestApi()
result, err := api.GeoIP(context.Background(), ip)
```
В случае нероссийского IP err будет nil, result будет &{nil}
Требуется доп проверка:

```
if result.Location == nil {
//  обрабатываем кейс с неопределенным адресом
}
```

**Comment by turboezh** [comment]
Добрый день.

Этот кейс описан в документации (не на сайте): https://confluence.hflabs.ru/pages/viewpage.action?pageId=204669119

>Если местоположение определить не удалось, то location = null

Если Вы имеете в виду обновление документации на сайте, то обратитесь пожалуйста в ДаДату. Мы сторонняя организация, которая просто опенсорсит клиент для их API.
