### ISSUE TITLE
Не находит кадастровый номер

### ISSUE THREAD

**Issue by AlexanderMatveev** [ekomobile/dadata#29]
Не находит номер `50:26:0151501:1400`, хотя во всех базах он есть. Пробую из кода, из песочницы на сайте, одинаково.
<img width="765" alt="Screenshot 2024-10-24 at 23 09 53" src="https://github.com/user-attachments/assets/f205602d-85c6-4fe9-8822-05994ce01893">

**Comment by educationisenemy** [comment]
Выглядит так что этого номера нет в базе данных DaData
Обратитесь к ним в [поддержку](https://support.dadata.ru/)

**Comment by AlexanderMatveev** [comment]
Ссылка на вопрос: https://support.dadata.ru/communities/1/topics/42614-ne-nahodit-kadastrovyij-nomer

**Comment by AlexanderMatveev** [comment]
Написал в поддержку, отпишу сюда результат
