### ISSUE TITLE
Нерепрезентативный README.MD

### ISSUE THREAD

**Issue by jarnsida** [ekomobile/dadata#7]
Ребят, вы бы в описании вставили os.SetEnv. 

Полчаса искал куда ключи класть, только из тестов смог найти.

И вообще, зачем вы их по умолчанию в параметры среды записали? Если мне надо, я буду их туда класть и оттуда доставить, но не всегда это нужно.

**Comment by turboezh** [comment]
Добрый день. Спасибо за замечание, дополним README (#8).

Переменными окружения пользоваться не обязательно. При необходимости можно передавать ключи напрямую:
```go
creds := client.Credentials{
    ApiKeyValue:    "<YOUR_API_KEY>",
    SecretKeyValue: "<YOUR_SECRET_KEY>",
}

api := NewSuggestApi(client.WithCredentialProvider(&creds))
```

Или можно реализовать интерфейс `client.CredentialProvider` любым удобным способом, и тянуть ключи, например, из БД или etcd.
